source "https://rubygems.org"

gem "roda"
gem "puma"
gem "sequel"
gem "markaby"
gem "tilt"
gem "rack-console"
gem "listen"
gem "zeitwerk"
gem "dotenv-rails"
gem "rack"
gem "sequel-hash_id"
gem "sqlite3", "~> 1.4"
gem "pry", "~> 0.13.1"
gem "mail"
